### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Alanjoose** [Hederblz/alien-task#26]
Deixem aqui os reports das alterações feitas no repositório.

**Comment by Alanjoose** [comment]
Removi os controllers duplicados e modifiquei o conteúdo destas.

**Comment by jonatas2021** [comment]
Participando na idealização e construção dos **Seeders** para sua finalização na data prevista.

**Comment by Hederblz** [comment]
Criação das factorys, participei da criação das migrations, seeders e dos models.

**Comment by ThierryMatheus** [comment]
Helder, estamos na sprint 3. Faz esse comentario lá agr
