### ISSUE TITLE
Report Sprint 3

### ISSUE THREAD

**Issue by ThierryMatheus** [Hederblz/alien-task#32]
Issue para os colaboradores comentarem todas as suas atividades relacionadas ao projeto.

**Comment by lilialnas** [comment]
Passando aqui e não vendo nada!! Que beleza hein!

**Comment by Alanjoose** [comment]
Foram realizadas as criações de controllers, factories, seeders, models e testes de database com seus relacionamentos. Devido a uma confusão de migrations e entidades, reiniciamos o projeto e estamos fazendo todos os passos até aqui.

**Comment by Alanjoose** [comment]
Foram realizadas as criações de novos relacionamentos aos models, refatoração das factories, modificação das migrations e modificação na chamada dos seeders. Juntamente com os testes em ambiente de terminal.

**Comment by Alanjoose** [comment]
Criei o crud de tarefas e ajudei a criar cud do usuário e histórico, e fiz uma correção de rotas resource.

**Comment by Hederblz** [comment]
Criação da entidade usuario, adição da funcionalidade de delete e updade para o usuario.

**Comment by jonatas2021** [comment]
Redefinimos o projeto, para a recriação das Models, Migrations, Seeders, Factories e Controllers de todas as entidades e dividimos por tabela para cada integrante do grupo. Sendo assim, para facilitar e explorar melhor o conhecimento.

**Comment by CaioSousa32** [comment]
Criei o crud de histórico, com as suas respectivas funcionalidades.

**Comment by jonatas2021** [comment]
De forma geral, fiquei com toda parte da entidade **Nota**, desde sua Criação até o Crud.

**Comment by Alanjoose** [comment]
Restaurei as views para o estado inicial devido a um conflito com as rotas do breeze.

**Comment by Alanjoose** [comment]
Alterei campos das tabelas para nullable.
