### ISSUE TITLE
Report de atividades da sprint 0

### ISSUE THREAD

**Issue by Alanjoose** [Hederblz/alien-task#6]

**Comment by Alanjoose** [comment]
Criei e fiz o commit do projeto <b>alientask</b> em laravel; e fiz parte da modelagem do banco de dados.

**Comment by jonatas2021** [comment]
Participei da criação lógica do modelo do banco de dados.

**Comment by jonatas2021** [comment]
Participei no desenvolvimento do questionário para pesquisas.

**Comment by jonatas2021** [comment]
Participei na criação das técnicas de pesquisas (Brainstorming).

**Comment by CaioSousa32** [comment]
Participei da criação do questionário para pesquisas.

**Comment by CaioSousa32** [comment]
Participei da criação do roteiro para a realização do Brainstorming.

**Comment by Hederblz** [comment]
Fiz parte da criação do modelo lógico bando de dados e do desenvolvimento do questionario.

**Comment by FlavioBatistaVS** [comment]
Participei da parte do desenvolvimento do questionário.

**Comment by FlavioBatistaVS** [comment]
Participei da parte do desenvolvimento do questionário

**Comment by FlavioBatistaVS** [comment]
Participei da parte do desenvolvimento do questionário

**Comment by FlavioBatistaVS** [comment]
Participei da parte do desenvolvimento do questionário criado.

**Comment by FlavioBatistaVS** [comment]
Participei da parte do desenvolvimento do questionario

**Comment by GabrielBarros9** [comment]
Participei da parte do desenvolvimento do questionario
